apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster-evaluation
  labels:
    app.kubernetes.io/name: evaluation-service
    app.kubernetes.io/component: evaluation
    app.kubernetes.io/part-of: togglemaster
type: Opaque
data:
  access-key: ${AWS_ACCESS_KEY_BASE64}
  secret-access-key: ${AWS_SECRET_KEY_BASE64}
  session-token: ${AWS_SESSION_TOKEN_BASE64}
